repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-yaml

- repo: https://gist.github.com/bsamseth/0abbcee0655e8023abc63c2c2b27c122
  rev: cda1f2c05d24849f19a28f1f4fa760136b4a0552
  hooks:
  - id: build-doc
